inherit_gem:
  decidim-dev: rubocop-decidim.yml

AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'

Rails/FilePath:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

